arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 2.0  # Aumentado de 0.005 a 2 segundos
  kinematics_solver_attempts: 3
  tip_name: link_5  # Definir el tip link del brazo
  root_name: base_link  # Definir el root link del brazo
gripper:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 2.0  # Aumentado de 0.005 a 2 segundos