cartesian_positions:
  home:
  - 0.0
  - 0.0
  - 0.3
  object_1:
  - 0.3
  - 0.0
  - 0.1
  object_2:
  - 0.2
  - 0.2
  - 0.1
  target_1:
  - -0.3
  - 0.0
  - 0.1
  target_2:
  - -0.2
  - 0.2
  - 0.1
gripper:
  close_time: 3.0
  closed_position: 0.8
  grip_force: 0.5
  open_position: 0.0
  open_time: 2.0
joint_positions:
  home:
  - 0.0
  - 1.57
  - 0.0
  - 0.0
  - 0.0
  pick_approach:
  - 2.8913163481255593
  - 0.5276990816987244
  - 0.49539816339744785
  - 2.088495408493621
  - 1.5707963267948966
  pick_position:
  - 2.8913163481255593
  - 0.5276990816987244
  - 0.29539816339744784
  - 1.988495408493621
  - 1.5707963267948966
  place_approach:
  - 3.0
  - 1.55
  - 0.7
  - 0.0
  - 1.8
  place_position:
  - 3.0
  - 1.3
  - 0.4
  - 0.0
  - 1.8
movement:
  approach_height: 0.15
  default_duration: 3.0
  max_acceleration_scaling: 0.1
  max_velocity_scaling: 0.1
  pick_height_offset: 0.02
  planning_attempts: 10
  planning_time: 10.0
objects:
- name: objeto1
  position:
  - 0.3
  - 0.0
  - 0.1
  size:
  - 0.05
  - 0.05
  - 0.05
- name: objeto2
  position:
  - 0.2
  - 0.2
  - 0.1
  size:
  - 0.03
  - 0.03
  - 0.08
obstacles:
- name: mesa
  position:
  - 0.0
  - 0.0
  - -0.01
  size:
  - 0.8
  - 0.8
  - 0.02
  type: box
- name: pared
  position:
  - 0.0
  - 0.5
  - 0.3
  size:
  - 1.0
  - 0.02
  - 0.6
  type: box
sequences:
  basic_demo:
  - action: move_joints
    description: "Ir a posici\xF3n inicial"
    target: home
  - action: open_gripper
    description: Abrir gripper
  - action: move_joints
    description: Acercarse al objeto
    target: pick_approach
  - action: move_joints
    description: "Posici\xF3n de agarre"
    target: pick_position
  - action: close_gripper
    description: Agarrar objeto
  - action: move_joints
    description: Levantar objeto
    target: pick_approach
  - action: move_joints
    description: Ir hacia destino
    target: place_approach
  - action: move_joints
    description: "Posici\xF3n de colocaci\xF3n"
    target: place_position
  - action: open_gripper
    description: Soltar objeto
  - action: move_joints
    description: Alejarse
    target: place_approach
  - action: move_joints
    description: Volver a home
    target: home
  cartesian_demo:
  - action: move_cartesian
    description: "Posici\xF3n inicial"
    target: home
  - action: open_gripper
    description: Abrir gripper
  - action: move_cartesian
    approach_height: true
    description: Acercarse al objeto 1
    target: object_1
  - action: move_cartesian
    description: Bajar al objeto 1
    target: object_1
  - action: close_gripper
    description: Agarrar objeto
  - action: move_cartesian
    approach_height: true
    description: Levantar objeto
    target: object_1
  - action: move_cartesian
    approach_height: true
    description: Ir hacia destino 1
    target: target_1
  - action: move_cartesian
    description: Bajar al destino
    target: target_1
  - action: open_gripper
    description: Soltar objeto
  - action: move_cartesian
    approach_height: true
    description: Alejarse
    target: target_1
  - action: move_cartesian
    description: Volver a home
    target: home
tolerances:
  joint: 0.1
  orientation: 0.1
  position: 0.02
workspace:
  x_max: 0.5
  x_min: -0.5
  y_max: 0.5
  y_min: -0.5
  z_max: 0.8
  z_min: 0.0
