cartesian_positions:
  blue_destination:
  - -0.26
  - 0.11
  - 0.1
  green_destination:
  - 0.25
  - 0.1
  - 0.1
  home:
  - 0.0
  - 0.0
  - 0.3
  object_1:
  - 0.3
  - 0.0
  - 0.1
  object_2:
  - 0.2
  - 0.2
  - 0.1
  target_1:
  - -0.3
  - 0.0
  - 0.1
  target_2:
  - -0.2
  - 0.2
  - 0.1
gripper:
  close_time: 3.0
  closed_position: 0.75
  grip_force: 0.5
  open_position: 0.0
  open_time: 3.0
joint_positions:
  blue_position:
  - 2.7414
  - 1.43
  - 0.562
  - 1.579
  - 1.5708
  green_position:
  - 0.4002
  - 2.06
  - 1.43
  - 2.78
  - 1.5708
  home:
  - 0.0
  - 1.57
  - 0.0
  - 0.0
  - 0.0
  pick_approach:
  - 2.37060674712753
  - 2.660387514354469
  - 0.49588604832424776
  - 2.239501466030221
  - 1.5707963267948966
  pick_position:
  - 2.37060674712753
  - 3.041592653589793
  - 1.6303328225357767
  - 2.9348265261407445
  - 1.5707963267948966
  place_position:
  - 3.0
  - 1.55
  - 0.7
  - 0.0
  - 1.8
movement:
  approach_height: 0.15
  default_duration: 3.0
  max_acceleration_scaling: 0.1
  max_velocity_scaling: 0.1
  pick_height_offset: 0.02
  planning_attempts: 10
  planning_time: 10.0
objects:
- name: objeto1
  position:
  - 0.3
  - 0.0
  - 0.1
  size:
  - 0.05
  - 0.05
  - 0.05
- name: objeto2
  position:
  - 0.2
  - 0.2
  - 0.1
  size:
  - 0.03
  - 0.03
  - 0.08
obstacles:
- name: mesa
  position:
  - 0.0
  - 0.0
  - -0.01
  size:
  - 0.8
  - 0.8
  - 0.02
  type: box
- name: pared
  position:
  - 0.0
  - 0.5
  - 0.3
  size:
  - 1.0
  - 0.02
  - 0.6
  type: box
sequences:
  basic_demo:
  - action: move_joints
    description: Ir a posicion inicial
    target: home
  - action: move_joints
    description: Acercarse al objeto
    target: pick_approach
  - action: move_joints
    description: Posicion de agarre
    target: pick_position
  - action: close_gripper
    description: Agarrar objeto
  - action: move_joints
    description: Levantar objeto
    target: pick_approach
  - action: move_joints
    description: Ir hacia destino
    target: place_position
  - action: open_gripper
    description: Soltar objeto
  - action: move_joints
    description: Volver a home
    target: home
  blue_cube_sequence:
  - action: move_joints
    description: Posicion inicial
    target: home
  - action: move_joints
    description: Acercarse al cubo azul
    target: pick_approach
  - action: move_joints
    description: Bajar al cubo azul
    target: pick_position
  - action: close_gripper
    description: Agarrar cubo azul
  - action: move_joints
    description: Levantar cubo azul
    target: pick_approach
  - action: move_joints
    description: Ir hacia destino azul
    target: blue_position
  - action: open_gripper
    description: Soltar cubo azul
  - action: move_joints
    description: Volver a home
    target: home
  green_cube_sequence:
  - action: move_joints
    description: Posicion inicial
    target: home
  - action: move_joints
    description: Acercarse al cubo verde
    target: pick_approach
  - action: move_joints
    description: Bajar al cubo verde
    target: pick_position
  - action: close_gripper
    description: Agarrar cubo verde
  - action: move_joints
    description: Levantar cubo verde
    target: pick_approach
  - action: move_joints
    description: Ir hacia destino verde
    target: green_position
  - action: open_gripper
    description: Soltar cubo verde
  - action: move_joints
    description: Volver a home
    target: home
tolerances:
  joint: 0.1
  orientation: 0.1
  position: 0.02
workspace:
  x_max: 0.5
  x_min: -0.5
  y_max: 0.5
  y_min: -0.5
  z_max: 0.8
  z_min: 0.0
